JBIDE-28098 : add quarkus telemetry usage (installs)
jbosstools/jbosstools-base pull request #718
Opened 2021-11-17 13:43 UTC by sbouchet

Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

2021-11-17 14:00 UTC, jeffmaury requested changes

2021-11-17 14:00 UTC, jeffmaury commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/reporting/JBossToolsComponents.java
> +		QUARKUS("org.jboss.tools.quarkus.feature", "org.jboss.tools.quarkus.runtime"),
I would chose org.jboss.tools.quarkus.core for the bundle as runtime is about embedding Quarkus which is using a pre release of Quarkus and may change drastically (chance of removal) in the future

2021-11-17 14:59 UTC, sbouchet commented
to be merged after #717

2021-11-18 09:09 UTC, jeffmaury approved these changes
LGTM

2021-11-18 09:19 UTC, merged