copied intellij-telemetry & made it compile (JBIDE-28396)
jbosstools/jbosstools-base pull request #760
Opened 2023-06-08 11:49 UTC by adietish

2023-06-19 07:45 UTC, sbouchet commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/configuration/TelemetryConfiguration.java
> +    public static final String KEY_MODE = "com.redhat.devtools.intellij.telemetry.mode";
why is it the same key as Intellij ?

2023-06-19 07:49 UTC, sbouchet reviewed
see above remarks

2023-06-19 08:34 UTC, adietish commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/event/UsageReporter.java
> +			eventSender = new TelemetrySender();
this is the main switch where we stop sending to google analytics but send to segment instead.

2023-06-20 07:46 UTC, adietish commented
@sbouchet: thanks for pointing out
> why is it the same key as Intellij
it now saves to a separate file with a separate key:
~/.redhat/org.jboss.tools.usage.internal.telemetry:
```
org.jboss.tools.usage.internal.telemetry.mode=DEBUG
```
The file is automatically created as soon as you agree to tracking of your usage. If it already exists, nothing in it is changed. So if you switch it to DEBUG (from NORMAL), your key is preserved.
In other words enablement is in a first step decided by the preferences (as it was before this PR). Then in a 2nd step segment telemetry decided upon the above file whether tracking information is sent to the NORMAL- or DEBUG-target or not sent at all (DISABLED).

2023-06-20 07:50 UTC, sbouchet commented
> @sbouchet: thanks for pointing out
> 
> > why is it the same key as Intellij
> 
> it now saves to a separate file with a separate key: **~/.redhat/org.jboss.tools.usage.internal.telemetry**
> 
> ```ini
> org.jboss.tools.usage.internal.telemetry.mode=DEBUG
> ```
> 
> The file is automatically created as soon as you agree to tracking of your usage. If it already exists, nothing in it is changed. So if you switch it to DEBUG (from NORMAL), your key is preserved. In other words enablement is in a first step decided by the preferences (as it was before this PR). Then in a 2nd step segment telemetry decided upon the above file whether tracking information is sent to the NORMAL- or DEBUG-target or not sent at all (DISABLED).

this is great.
it also means users need to re-enable telemetry if they agreed before, as the key changed? 
this is ok, since we moved out from GA to Segment, it makes sense to re-ask users to agree on telemetry again. 
CC @fbricon for the record.

2023-06-20 12:43 UTC, sbouchet commented
> @sbouchet, @fbricon:
> 
> > it also means users need to re-enable telemetry if they agreed before, as the key changed?
> 
> Unfortunately this isn't the case. If you agreed to the dialog ("do you allow us to report usage?") and your decision made it to the preferences, then things stay as they are, you are not asked again, reporting wont happen. This is the case because usage queries the preferences in a first step and only then queries segment/telemetry. If we wanted to force a new ack onto users, we'd have to reset the preferences value. I'd argue that there's no change in data, we only send to a different storage. A given agreement therefore should stay valid. If this wasn't the case we would have had to query people in telemetry again when we switched from woopra to amplitude.
> 
> There's a 2nd shortcoming: the value in the telemetry config file is only loaded once, when queried for the first time. In other words, if you change the value while it is running, the change is not taken into account. It only is when Eclipse is restarted.

Ah thanks for the explanation. i was trying to understand if the actual users that are sending to GA will get a new dialog asking again. It's not, because this dialog does not look into the key, but a preference value.
So all users that ack fortelemetry will send now to segment without a new question.
It's not that i want to ask users about the changes, i'll make a annoucement on the blog about this ( changing telemetry back from GA to Segment ) to make it publicly visible.

2023-06-20 12:47 UTC, sbouchet submitted a review, later dismissed
LGTM

2023-06-20 13:06 UTC, fbricon commented
Since we're collecting exactly the same data, only changing the processing backend, and everything still abides by the Red Hat privacy statement the users agreed on, we don't need to ask again

2023-06-20 15:16 UTC, fbricon requested changes
a bunch of new files have 2022 or 2022 in their copyright header. If the code was copied from somewhere else, it'd be nice to link to the original code

2023-06-20 15:16 UTC, fbricon commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/telemetry/TelemetrySender.java
> +package org.jboss.tools.usage.telemetry;
header

2023-06-20 18:05 UTC, adietish commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/service/IDE.java
> +import org.jboss.tools.usage.internal.environment.eclipse.IEclipseUserAgent;
I'd basically agree with you but if done consistently this would lead to lots of changes. I'll limit this to a "sane" extent

2023-06-20 18:19 UTC, adietish commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/util/TimeUtils.java
> +public class TimeUtils {
yes, ex. in ShutdownMessage via static import `TimeUtils.toLocalTime`:
```
       private ShutdownMessage(ServiceFacade service) {
            this(toLocalTime(ApplicationManager.getApplication().getStartTime()), service);
```

2023-06-20 18:44 UTC, adietish commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/service/segment/IdentifyTraitsPersistence.java
> +    private static final Path FILE = Directories.RED_HAT.resolve("segment-identify-traits.json");
In other words, you want Eclipse and IntelliJ to use different traits? Wouldn't it make sense to know if a user is using Eclipse and IntelliJ?

2023-06-21 12:39 UTC, adietish commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/service/TelemetryServiceFactory.java
> +        Environment environment = builder.plugin(plugin).build();
I agree, doing.

2023-06-21 14:24 UTC, adietish commented
@fbricon thanks for the inputs. Corrected these, please re-review.

2023-06-22 08:35 UTC, sbouchet submitted a review, later dismissed
LGTM

2023-06-22 13:31 UTC, fbricon commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/service/segment/SegmentBroker.java
> +    }
indentation is meh

2023-06-22 13:32 UTC, fbricon commented on usage/plugins/org.jboss.tools.usage/src/org/jboss/tools/usage/internal/telemetry/core/service/segment/IdentifyTraits.java
> + * Traits that the segment broker sends with am identify event.
an indentify event

2023-06-22 13:36 UTC, fbricon commented
@adietish feel free to merge once the small nits are addressed

2023-06-22 15:14 UTC, fbricon approved these changes

2023-06-22 15:21 UTC, merged